name: Schedule AWS Glue Job

on:
  schedule:
    # Schedule to run at 4:10 PM UTC every day
    - cron: '10 16 * * *'

jobs:
  trigger-glue-job:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Start the Glue job
      - name: Start AWS Glue job
        run: |
          aws glue start-job-run --job-name partitioningdata
